name: Tests

on:
  pull_request:
    types: [opened, edited, reopened]
    branches: [master]

jobs:
  test-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "oracle"

      - uses: gradle/gradle-build-action@v2

      - run: chmod +x gradlew

      - name: Run
        run: ./gradlew clean test

      - uses: actions/upload-artifact@v3
        with:
          name: Report
          path: build/reports/tests/test
